# Generated by Django 4.0.2 on 2022-02-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('propagate', models.BooleanField(default=False, help_text="If set then this environment will propagate it's configuration values down to lower environments")),
                ('promotes_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotes_to', to='configuration.environment')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('str_value', models.TextField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='configuration.environment')),
            ],
        ),
    ]
