# Generated by Django 4.0.2 on 2022-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvalue',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
